[package]
name = "lines"
version = "0.2.0"
authors = ["Ryan Fowler <ryan.fowler19@gmail.com>"]
edition = "2021"

[profile.release]
codegen-units = 1
debug = false
lto = "fat"
opt-level = 3

[dependencies]
bytecount = { version = "0.6" }
clap = { version = "3.2", features = ["derive"] }
crossbeam = { version = "0.8" }
fnv = { version = "1.0" }
ignore = { version = "0.4" }
jemallocator = { version = "0.5" }
num_cpus = { version = "1.13" }
num-format = { version = "0.4" }
phf = { version = "0.10", features = ["macros"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = { version = "1.0" }
tabled = { version = "0.7" }
